import { Character } from "@/interfaces"
import { GetStaticProps, NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { useRouter } from "next/router"

interface Props {
  characters: Character[]
}

const Home: NextPage<Props> = ({ characters }) => {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-auto">
        <h1 className="text-5xl font-bold mt-10 text-center">Amiibos</h1>
        <ul className="grid md:grid-cols-4 sm:grid-cols-2 gap-3 py-3">
          {characters
            ? characters.map((character) => (
                <li
                  className="flex flex-col items-center justify-end"
                  key={character.tail}
                >
                  <Image
                    src={character.image}
                    alt={character.name}
                    height={300}
                    width={200}
                    onClick={() => router.push(`characters/${character.tail}`)}
                  />
                  <h2 className="text-xl">{character.name}</h2>
                </li>
              ))
            : null}
        </ul>
      </main>
    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(
    "https://amiiboapi.com/api/amiibo?gameseries=The Legend of Zelda"
  )
  const json = await res.json()
  const data = json.amiibo.slice(4, 24)

  return {
    props: { characters: data },
  }
}
