// Generated by https://quicktype.io

export interface Character {
  amiiboSeries: string
  character: string
  gameSeries: string
  head: string
  image: string
  name: string
  release: string
  tail: string
}
